defaults:
  - _self_



commit0_config:
  base_dir: repos
  dataset_name: "wentingzhao/commit0_docstring"
  dataset_split: "test"
  repo_split: "simpy"
  num_workers: 10

aider_config:
  llm_name: "claude-3-5-sonnet-20240620"
  use_user_prompt: false
  user_prompt: "Here is the Task:\n Your task is to iteratively implement the each function that is 'NotImplementedError('IMPLEMENT ME HERE')' in these files until there are no more 'NotImplementedError('IMPLEMENT ME HERE')' and pass the unit tests.\nMake sure you read the files carefully.\nYour output should be the edited code files.\nUse the above instructions to modify the supplied files.\nDo not change the names of existing functions or classes, as they may be referenced from other code like unit tests, etc.\nOnly use standard python libraries, do not suggest installing any packages."
  use_repo_info: false
  use_unit_tests_info: false
  use_reference_info: false
  use_lint_info: false
  pre_commit_config_path: .pre-commit-config.yaml
  run_tests: True
  max_repo_info_length: 10000
  max_unit_tests_info_length: 10000
  max_reference_info_length: 10000
  max_lint_info_length: 10000

hydra:
  run:
    dir: ./hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}