spec2repo/minitorch:
  "0.4":
    python: "3.9"
    install: "python -m pip install -Ue ."
    packages: "requirements.txt"
    pip_packages:
      - "datasets==2.4.0"
      - "embeddings==0.0.8"
      - "networkx==2.4"
      - "plotly==4.14.3"
      - "pydot==1.4.1"
      - "python-mnist"
      - "streamlit==1.12.0"
      - "streamlit-ace"
      - "torch"
      - "watchdog==1.0.2"
      - "numba==0.60"
    test_cmd: "pytest"

spec2repo/tinydb:
  "4.8":
    python: 3.11
    install: "python -m pip install --upgrade pip twine; pip install poetry; poetry install"
    test_cmd: "pytest"
