spec2repo/minitorch:
  "1.0":
    python: "3.9"
    install: "python -m pip install -r requirements.txt; python -m pip install -r requirements.extra.txt; python -m pip install -Ue ."
    packages: "requirements.txt"
    pip_packages:
      - "numba==0.60"
    test_cmd: "pytest"

spec2repo/tinydb:
  "1.0":
    python: 3.11
    install: "python -m pip install --upgrade pip twine; pip install poetry; poetry install"
    test_cmd: "pytest"
