defaults:
  - _self_

# shared in all steps
dataset_name: wentingzhao/commit0_docstring
dataset_split: test

# clone related
base_dir: repos/
repo_split: all

# build related
num_workers: 8
key_path: commit0/configs/public_keys.json

# set up git user
git_user: git  # by default, git user is called git

# test related
backend: local
branch: ai
timeout: 1_800

# save related
github_token: null
