name: system

on:
  pull_request:
  push:
    branches: [main]

jobs:
  system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Set up Python
        run: uv venv --python 3.12
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install the project
        run: uv sync
      - name: Set up commit0
        run: uv run commit0 setup simpy
      - name: Build docker images
        run: uv run commit0 build simpy
      - name: Get tests
        run: uv run commit0 get-tests simpy
      - name: Test
        run: uv run commit0 test simpy tests/test_event.py::test_succeed --reference
      - name: Evaluate
        run: uv run commit0 evaluate simpy --reference
      - name: Lint
        run: uv run commit0 lint commit0/harness/lint.py
      - name: Save
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          uv run commit0 save simpy test-save-commit0 master
