name: system

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Set up Python
        run: uv venv --python 3.12
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install the project
        run: uv sync
      - name: Clone
        run: uv run commit0 clone
      - name: Setup
        run: uv run commit0 build
      - name: Test
        run: uv run commit0 test
      
